### ISSUE TITLE
Fixed Width/Responsive Layout

### ISSUE THREAD

**Issue by ATrecha** [DrewDahlman/Perfect-Masonry#1]
Hello!

I have managed to created a full width version here - http://rantaconsulting.net/Client/PHR/index-isotope-masonry.html

I would like to use Perfect-Masonry in a bootstrap .container (default 1170px width center column).

I've tried to set this up, but the masonry ignores the .container parameters and spills out of the container attempting to display the full width of the viewport.

Any help would be appreciated.

Thanks!

**Comment by DrewDahlman** [comment]
Check out the jQuery plugin vs this repo. This is here for archival purposes - https://github.com/DrewDahlman/Mason

Please make an issue there.
